export const markers = [
    {
        latitude : 42.0215777,
        longitude : -93.6490166,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "AJ's Ultra Lounge",
        website: 'https://ajsultralounge.com/',
        key : '1',
    },
    {
        latitude : 42.0200674,
        longitude : -93.6505774,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "Bar la Tosca",
        website: 'https://www.barlatosca.com/',
        key : '2',
    },
    {
        latitude : 42.021393,
        longitude : -93.65002,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: 'BNC Field House - Bar & Grill',
        website: 'https://bncfieldhouse.com/',
        key : '3',
    },
    {
        latitude : 42.0219405,
        longitude : -93.6504618,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "Cy's Roost",
        website: '',
        key : '4',
    },
    {
        latitude : 42.0209415,
        longitude : -93.6482558,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "Es Tas Bar and Grill",
        website: 'https://estastacos.com/',
        key : '5',
    },
    {
        latitude : 42.0249089,
        longitude : -93.6124551,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "London Underground",
        website: 'https://www.theundergroundames.com/',
        key : '6',
    },
    {
        latitude : 42.022363,
        longitude : -93.6503347,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "Mickey's Irish Pub",
        website: 'https://places.singleplatform.com/mickeys-irish-pub/menu?ref=google',
        key : '7',
        
    },
    {
        latitude : 42.021231,
        longitude : -93.6512429,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "Outlaws",
        website: '',
        key : '8',
        
    },
    {
        latitude : 42.0218582,
        longitude : -93.6498812,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "Paddy's Irish Pub",
        website: '',
        key : '9',
        
    },
    {
        latitude : 42.0204323,
        longitude : -93.6504335,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "The Blue Owl Bar",
        website: 'https://www.instagram.com/theblueowlbar/',
        key : '10',
        
    },
    {
        latitude : 42.0251756,
        longitude : -93.6565113,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: "Thumbs",
        website: 'https://www.facebook.com/thumbslife/?_rdr',
        key : '11',
        
    },
    {
        latitude : 42.0210799,
        longitude : -93.6503498,
        latitudeDelta : .01,
        longitudeDelta : .01,
        name: 'Welch Ave. Station',
        website: 'http://www.welchave.com/',
        key : '12',
    },
    
    
]; 